---
title: "Steven's transducer (power) with porportional noise"
format: html
editor: visual
---

```{r}
library(tidyverse)

list.files("R", full.names = TRUE) |>  walk(source)
```

Values:

```{r}

p <- 0.2

```

Transducer

```{r}
mu_power_fun <- function(x, p){
  x^p
}


r_power_vectorized_fun <- function(x, p) {
  mu <- mu_power_fun(x, p)
  noise <- rnorm(length(x), # we create as many samples as values of xs we have
                 mean = 0, 
                 sd = 0.08) # Let's use the third component for the noise
  noise_2 <- noise*mu #lo he hecho así, quizá está mal
  
  mu + noise_2
}
```

Raw_data:

```{r}

data_raw <- crossing(x = seq(0, 1, .05), n = 1:5000) |> 
  mutate(y = r_power_vectorized_fun(x, p))

```

Plot raw data:

```{r}

data_raw |> ggplot() + 
  geom_point(aes(x = x, y = y))

```

Plot with pdf distribution:

No lo entiendo :,()

```{r}
pdf_fun_power <- function(y, p, x) {
  dnorm(y, 
        mean = mu_power_fun(x, p), 
        sd = p[3]*y) 
}


pdf_power <- crossing(x = seq(0, 1, .05), n = 1:5000) |> 
  mutate(y = r_power_vectorized_fun(x, p)) |> 
  mutate(f = pdf_fun_power(y, c(P1, P2, P3), x))

pdf_power |> 
  ggplot(aes(x = y, y = f)) +
  facet_wrap(vars(x), labeller = "label_both") +
  geom_point()
```

```{r}
pdf_power |> 
  ggplot(aes(x = y, y = f)) +
  facet_wrap(vars(x), labeller = "label_both", nrow = 1) +
  geom_line() +
  coord_flip()
```



```{r}
data <- data_raw |> group_by(x) |>  
  summarise(mean_y= mean(y), sd_y=sd(y)) |> 
  ungroup() |> 
  mutate(dmu = dmu(x, mean_y)) |> 
  drop_na() |> 
  mutate(delta = dmu/sd_y)
```

Plot mu (mean responses)

```{r}
data |> ggplot() + geom_line(aes(x = x, y= mean_y))
```

Plot delta (discrimination):

```{r}
data |> ggplot() + geom_line(aes(x= x, y= delta)) 
```
